### ISSUE TITLE
Sync MySQL error

### ISSUE THREAD

**Issue by lasalesi** [libracore/mailchimpconnector#2]
The sync process aborts with

 mailchimpconnector.mailchimpconnector.page.sync_mailchimp.sync_mailchimp.sync_contacts

	Traceback (most recent call last):
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rq/worker.py", line 713, in perform_job
		rv = job.perform()
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rq/job.py", line 556, in perform
		self._result = self._execute()
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rq/job.py", line 562, in _execute
		return self.func(*self.args, **self.kwargs)
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 119, in execute_job
		frappe.db.rollback()
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 768, in rollback
		self.sql("rollback")
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 176, in sql
		self._cursor.execute(query)
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
		result = self._query(query)
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
		conn.query(q)
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 859, in query
		self._execute_command(COMMAND.COM_QUERY, sql)
	  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in _execute_command
		raise err.InterfaceError("(0, '')")
	InterfaceError: (0, '')

**Comment by lasalesi** [comment]
Unfortunately not reproducible... The error occurred after a complete sync. Possibly it was raised by the sync start log, which was kept open too long (resolved).

**Comment by lasalesi** [comment]
Source was a timeout based on the frappe.log_error(), which was triggered in the long worker. Moved this before the start of the long worker, eliminated the issue.
